services:
  app:
    image: openjdk:17
    environment:
      - SPRING_APPLICATION_NAME=lab79InContainer 
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mydb
      - SPRING_DATASOURCE_USERNAME=test  
      - SPRING_DATASOURCE_PASSWORD=test  
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver 
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app/labSeven-0.0.1-SNAPSHOT.jar"]
    volumes:
      - ./target:/app  
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"